-- Auto-generated by gen_spritesheet_data.py
-- Spritesheet: goblin

INSERT INTO animations VALUES ('walk', 'goblin', 0, 1, 8, '75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('carry', 'goblin', 1, 1, 8, '75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('idle', 'goblin', 2, 1, 9, '75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('watering', 'goblin', 3, 1, 5, '75,75,75,75,75');
INSERT INTO animations VALUES ('hurt', 'goblin', 4, 0, 8, '75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('death', 'goblin', 5, 0, 13, '75,75,75,75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('doing', 'goblin', 6, 0, 8, '75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('run', 'goblin', 7, 1, 8, '75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('jump', 'goblin', 8, 0, 9, '75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('roll', 'goblin', 9, 0, 10, '75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('axe', 'goblin', 10, 0, 10, '75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('mining', 'goblin', 11, 0, 10, '75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('swimming', 'goblin', 12, 1, 12, '75,75,75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('hamering', 'goblin', 13, 0, 23, '75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('attack', 'goblin', 14, 0, 10, '75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('casting', 'goblin', 15, 0, 15, '75,75,75,75,75,75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('waiting', 'goblin', 16, 1, 9, '75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('reeling', 'goblin', 17, 0, 13, '75,75,75,75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('caught', 'goblin', 18, 0, 10, '75,75,75,75,75,75,75,75,75,75');
INSERT INTO animations VALUES ('dig', 'goblin', 19, 0, 13, '75,75,75,75,75,75,75,75,75,75,75,75,75');
